### ISSUE TITLE
$ value for position is not displayed

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Hydra-mining-ui#102]
Expected state:
As user if i have liquidity position
I want to see value of this position in $ value

Current state:
$ value for liquidity positions is not displayed

<img width="1109" alt="Screenshot 2023-01-03 at 22 17 15" src="https://user-images.githubusercontent.com/97346452/210444296-e8116ba7-72db-4c7b-ba5d-5030d57ac9f8.png">

**Comment by obsivac-cleevio** [comment]
Issue was with missing LRNA spot price, position without LRNA now display prices if spot price is available
