### ISSUE TITLE
Unusual behaviour on Recent Activies

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#109]
When the recent tx sidebar is "full" (presumably 10 tx?) it is removing the top tx when I start a new one, and not the oldest tx

**Recent tx**
![image](https://user-images.githubusercontent.com/97540577/210554235-096a3238-be48-4f10-bf13-33de57fbc31d.png)
**Initiate new tx, 2nd most recent tx removed**
![image](https://user-images.githubusercontent.com/97540577/210554415-777ce02d-0ea3-435e-b03c-6f03c5e83548.png)
**tx successful**
![image](https://user-images.githubusercontent.com/97540577/210554455-17a34f3e-d5f5-4dac-b903-b0217ac4ff41.png)
**Initiate new tx, previously successful tx removed**
![image](https://user-images.githubusercontent.com/97540577/210554530-49240932-3837-42a0-b9f7-2c426bd52089.png)
![image](https://user-images.githubusercontent.com/97540577/210554593-e9ca8962-ad96-4d35-99e2-55a248264898.png)

**Comment by tomashapl1** [comment]
@lolmcshizz Cannot reproduce, could you check it again ? 🙏
