### ISSUE TITLE
Total value in Pools not working for "My positions"

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#110]
When I select "My positions" toggle, the "Value in Pools" drops to $0 - however, I have several liquidity positions so there should be a value calculated here

![image](https://user-images.githubusercontent.com/97540577/210556445-689393cc-f0d6-4c8b-bc8b-d04d3179bdb1.png)

**Comment by obsivac-cleevio** [comment]
Fixed [here](https://github.com/galacticcouncil/Hydra-mining-ui/commit/d7cea333b21faca64dafa78a6d2748bba5ebc1b4)
