### ISSUE TITLE
"Total locked" not functioning correctly

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#118]
On the "POOLS" page, under each pool there is "Total locked-"

<img width="456" alt="image" src="https://user-images.githubusercontent.com/97540577/210741379-63ead11a-1bc7-40f8-b10f-da05550130a4.png">

This should behave in the following way:

- If user does not have a position, it should not show this bar at all
- If user does have a position/s, it should provide a total of their Liquidity Positions

There is no need for reference to farming in this version, due to LM not being available - so that can stay absent.

**Comment by DuriSK** [comment]
sum of all LP position under given asset*$price from SDK
