### ISSUE TITLE
Non-transferrable tokens not including all types

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#119]
I have a total balance of ~4 800 HDX
- 2 000 locked in democracy
- 1 814 reserved

In the UI on the wallet page, I am able to see that I only have 992 HDX that are transferrable, however, the extended information only shows 2 000 locked, it does not show the reserved.

- Add reserved to the extended information
- If possible, add the "type" of lock in the wallet i.e. 2 000 locked in democracy
- if possible +, add detail on whether the democracy locks have expired
- if possible ++, add "Clear expired democracy locks" so that user doesn't need to venture into polkadot.js apps to clear locks (see final image)

<img width="721" alt="image" src="https://user-images.githubusercontent.com/97540577/210743760-1d966f40-99d1-4ad2-b707-c9563e838338.png">

<img width="775" alt="image" src="https://user-images.githubusercontent.com/97540577/210743688-9824b9ab-8136-42f1-b75c-6154b710093d.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/97540577/210744584-295c39df-83be-458b-aff4-feaca460418b.png">

**Comment by DuriSK** [comment]
For new attributes:
Reserved: system.account().reserved
Locked in Vesting:balances.locks() with id `ormlvest`
Locked in Democracy:balances.locks() with id `democrac`

Tokens are always HDX for Hydra, BSX for Basilisk
https://www.figma.com/file/eqzR2azTracqA8Vv0y4GUv/%F0%9F%96%A5--Hydra-%7C-Desktop-Library?node-id=4284%3A54933&t=Debkwax7Md0d9YSR-4
