### ISSUE TITLE
Inconsistencies in PAY WITH/ YOU GET/ Buy/ Sell

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#37]
**Issue related to "recent activities" / notification flow implementation**

**Example:** I enter 1 DAI into the "YOU GET" field (so I am buying DAI for HDX, or selling HDX for DAI), when my transaction is submitted, processing and completed it is labelled in the notification flow as "Buy xxxx HDX for 1 DAI submitted" - which is incorrect.

![image](https://user-images.githubusercontent.com/97540577/206179134-85edcb55-4079-4d4e-8644-473e1462c51c.png)

**Comment by jak-pan** [comment]
Should be Buy 1 DAI for xxx HDX

**Comment by lolmcshizz** [comment]
Moved to trade page repo
