### ISSUE TITLE
0 transaction fee for changing fee payment asset

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#40]
The transaction fee is displayed as 0 when trying to change your fee payment asset (the same case regardless of which asset is selected)

![image](https://user-images.githubusercontent.com/97540577/206182797-9aaf0eb4-3b03-44cc-9383-b26ca181a7e9.png)

**Comment by jak-pan** [comment]
This might be problematic as this is a "free" transaction API doesn't show anything. We could benchmark some generic transaction instead. (You're paying the tx fee in the selected asset)
