### ISSUE TITLE
Mobile: Fix active style for wallet (if selected)

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#41]
When you select "Trade" page - you have the below active state, however, when you select "Wallet" you do not get the same active state

![image](https://user-images.githubusercontent.com/97540577/206183298-3bf51310-8699-4b40-93b6-c8b1005e30d2.png)

**Comment by vkulinich-cl** [comment]
@lolmcshizz could re-test it? Looks like it already works

**Comment by lolmcshizz** [comment]
Hey @vkulinich-cl - still not working for me in chrome on android phone.

See below active state on trade page but nothing on wallet page.

![Screenshot_20221215_090810_Chrome](https://user-images.githubusercontent.com/97540577/207818680-2245f6a1-8260-4132-b7d2-83f4c251e23f.jpg)
![Screenshot_20221215_090820_Chrome](https://user-images.githubusercontent.com/97540577/207818684-327c6dd0-5eb1-4a92-b91f-43eb1cb1faa7.jpg)

**Comment by vkulinich-cl** [comment]
Should be fixed the latest changes

**Comment by lolmcshizz** [comment]
Appears to have not been resolved
