### ISSUE TITLE
Buy/ Sell buttons do not change assets loaded on trade page

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Hydra-mining-ui#45]
On the wallet page, when you select BUY or SELL next to a token, the trade page loads but it always loads "PAY WITH" HDX, the PAY WITH or YOU GET should be pre filled based on the asset you select and whether you choose to buy or sell

![image](https://user-images.githubusercontent.com/97540577/206185461-7b78015b-fd3e-4795-91f2-b24cc84f6d98.png)

![image](https://user-images.githubusercontent.com/97540577/206185506-c28cdabb-688e-4467-a156-48a1bd61f172.png)

**Comment by DuriSK** [comment]
If user clicks on BUY action button on asset list, then trade screen should be displayed and given asset should be preselected in "YOU GET" asset selector.

If user clicks on  SELL action button on asset list, then trade screen should be displayed and given asset should be preselected in "PAY WITH" asset selector.

https://www.notion.so/Wallet-9109f05941de4d1596fd290c26843fa7#02d5470f5d6149769fd7809f4c0bd0ff
