### ISSUE TITLE
Disable add liquidity button, if user wants to add more liquidity than its available

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Hydra-mining-ui#81]
Given user wants to add liquidity
And he start entering amount, which he wants to provide
And he wants to provide too much 
Than he should be informed, that he reached treshold
And Add liquidity button should be disabled

This behaviour was described in https://github.com/galacticcouncil/Hydra-mining-ui/issues/70
Please, if user wants to add too much liquidity, and we display disclaimer, also block Add Liquidity button, based on provided design

![image](https://user-images.githubusercontent.com/97346452/209842451-4f2f0a7c-2658-4ca7-9861-28659870fbea.png)

**Comment by vkulinich-cl** [comment]
Fixed by another PR
