### ISSUE TITLE
If user doesnt have connected wallet, show wallet connection flow first, when user is trying to add liquidity

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Hydra-mining-ui#95]
Current state:
Given user is on pools screen, and he doesnt have wallet connected
When he clicks on Add liquidity button
Than he see Add liquidity screen

To be:
If user doesnt have wallet connected, and he clicks on Add liquidity button
Then wallet connection flow should be displayed
And when user connects wallet, than Add liquidity screen (for asset which user selected) should be displayed

**Comment by tomashapl1** [comment]
@DuriSK Now we have add liquidity button disabled:

![image](https://user-images.githubusercontent.com/104817596/210804677-46f35b2a-df86-4dd5-8f20-5de11ae3bfbe.png)

Is it enough ? or you want to deal by expected behaviour with it ?

**Comment by vkulinich-cl** [comment]
The ticket is not relevant anymore
